### ISSUE TITLE
Can not run the test example for s-jSDM

### ISSUE THREAD

**Issue by CaiWang0503** [iDiv-sCom/jSDM-Help#1]
Every time when I run this command it always causes RStudio forced exit.
Why is that？
<img width="570" alt="Screen Shot 2020-05-07 at 1 04 53 PM" src="https://user-images.githubusercontent.com/48045062/81256779-14e67b80-9064-11ea-87e4-7553953b6b77.png">
<img width="1267" alt="Screen Shot 2020-05-07 at 1 02 08 PM" src="https://user-images.githubusercontent.com/48045062/81256802-2596f180-9064-11ea-9963-2f54486f68ce.png">

**Comment by florianhartig** [comment]
Hi CaiWang0503,

was this problem solved? If so, can you tell us what the problem was? As side note, questions that are specific to a software problem are probably faster answered if you post them on the GitHub repositories of the respective software packages, in this case https://github.com/TheoreticalEcology/s-jSDM

Best,
Florian

**Comment by CaiWang0503** [comment]
yes, it solved, I updated to r 3.6.3 and deleted the old version, it works.

**Comment by florianhartig** [comment]
Thanks!
